### ISSUE TITLE
guidelines link is missing

### ISSUE THREAD

**Issue by gocadimic** [standardshub/markdown_guidelines#23]
<img width="689" alt="Screenshot 2023-01-19 at 15 15 50" src="https://user-images.githubusercontent.com/19475071/213471891-ac192182-d0e8-4faf-a1b7-97599308e43a.png">

I noticed that the Guidelines are missing, presuming that the content is still being updated?

**Comment by jpradocueva** [comment]
@gocadimic, good catch. I believe that this guideline is in the old OMA wiki. I need to check it out.

**Comment by jpradocueva** [comment]
Resolved.
