### ISSUE TITLE
misplaced recommendations

### ISSUE THREAD

**Issue by gocadimic** [standardshub/markdown_guidelines#24]
<img width="720" alt="Screenshot 2023-01-19 at 15 19 36" src="https://user-images.githubusercontent.com/19475071/213473973-453cef58-6e59-4fc9-8d75-635efe4c185f.png">

See Issue #23 which refers to the missing "_create .svg images_" Guideline.

**Comment by jpradocueva** [comment]
Guidelines are uploaded to https://docs.google.com/document/d/194oEy2GrUdLafICeKUxPVH8zX9okZd_D/edit?usp=sharing&ouid=112978134087833973902&rtpof=true&sd=true

**Comment by jpradocueva** [comment]
resolved.
