### ISSUE TITLE
Updates to `Code with Syntax Highlighting 

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#3]
### Code With Syntax highlighting
- [x] highlighting word  is incorrectly spelled in the title and description  
- [x] In addition to having an example of how it is displayed, we need to add an example of how it is written in the markdown.

https://markdown.standardshub.io/md2html-extended#code-with-syntax-highlighing

**Comment by gocadimic** [comment]
Done in PR #10.

**Comment by jpradocueva** [comment]
Merged.
