### ISSUE TITLE
Add Table link

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#39]
![image](https://user-images.githubusercontent.com/3258579/217413554-d1df0172-08ed-4154-be6a-4dfa11f27b3a.png)

**Comment by jpradocueva** [comment]
@gocadimic's distribution of the constructors in this table looks different from the table dedicated to HTML. I think it will be easier for the user to have a similar layout and colors in this table.

**Comment by gocadimic** [comment]
@jpradocueva, constructors have been changed in line with a new structure. 
Do you think we should reconsider both diagrams again? Or am I missing something?

**Comment by jpradocueva** [comment]
@gocadimic let's have a chat on Monday, Feb 13.
