### ISSUE TITLE
Add examples of how the content is displayed

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#4]
https://markdown.standardshub.io/md2html-extended#further-links

Every markdown constructor should have an example of how it is written in markdown and how it is displayed in HTML.
The `Further Links` is missing how it is displayed in HTML.

Each constructor section should have the same structure, how it is written in markdown and how it is displayed in HTML.

**Comment by gocadimic** [comment]
Please see PR #14

**Comment by jpradocueva** [comment]
Resolved by #14
