### ISSUE TITLE
Add links to rowspan and colspan

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#40]
I suggest adding a link to those elements to the HTML table https://markdown.standardshub.io/#html-tables. That table contains some examples.

![image](https://user-images.githubusercontent.com/3258579/217414064-5e7c1ea7-daa9-4957-aaa5-604a13daaebe.png)

**Comment by gocadimic** [comment]
Resolved at PR #43.

**Comment by jpradocueva** [comment]
#52
