### ISSUE TITLE
Add new diagram to Advance Constructors section

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#41]
Add this diagram with the correct links to the new section `Advance Constructors` in the md2thml introduction.

![image](https://user-images.githubusercontent.com/3258579/218369078-4ffcaff7-e1fd-4c96-93eb-8b000afb3670.png)

**Comment by gocadimic** [comment]
Please clarify which diagram you are referring to. Do you mean "extended-md-diagram"?
I am not sure what graph should be presented in the new section Advance Constructors?
Please see PR #42.

**Comment by jpradocueva** [comment]
@gocadimic I have added above the image to insert.

**Comment by gocadimic** [comment]
@jpradocueva, please see PR #44. Minor changes have been made.
We should discuss which one would stay.
