### ISSUE TITLE
Grammar issue in Advanced Constructors section

### ISSUE THREAD

**Issue by TBRetro** [standardshub/markdown_guidelines#42]
In the section [MD2HTML App > Introduction > Advanced Constructors] it says the following,

"These instructions **have are** interpreted by the MD2HTML App to create PDF and HTML documents."

I believe the word "have" should be removed.

**Comment by jpradocueva** [comment]
@gocadimic Thomas from Retrovirux has been very kind and suggested some grammar changes to the one statement. Could you please prepare the pull request to address his comment? Thanks. J

**Comment by gocadimic** [comment]
Resolved at PR #43.

**Comment by jpradocueva** [comment]
@gocadimic We closed the PR that had a resolution for this. Could you please revisit PR #43 and see what we need to rescue into a new PR?

**Comment by gocadimic** [comment]
@jpradocueva, I will rectify that along with new updates with the graph and links. Then, I can create a new PR to join all.

**Comment by gocadimic** [comment]
Resolved in PR #52.

**Comment by jpradocueva** [comment]
Done!
