### ISSUE TITLE
Update Horizontal Rule link 

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#53]
![image](https://user-images.githubusercontent.com/3258579/220183356-aa2ff913-c646-4c42-a1e7-0396cacb8cd6.png)

The `Horizontal Rule` link should be pointing to https://markdown.standardshub.io/formatting#horizontal-rule

**Comment by gocadimic** [comment]
Resolved in PR #52.

**Comment by jpradocueva** [comment]
Done!
