### ISSUE TITLE
Update Ignoring Markdown Formatting link

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#54]
![image](https://user-images.githubusercontent.com/3258579/220183602-2df026f9-f800-47d7-84b2-3d16c22891bd.png)

The `Ignoring Markdown Formatting` link should be pointed out to https://markdown.standardshub.io/formatting#ignore-markdown-formatting

**Comment by gocadimic** [comment]
Resolved in PR #52.

**Comment by jpradocueva** [comment]
Done!
