### ISSUE TITLE
Add explanation to `Paragraph` section

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#6]
See the content to add to the "Paragraph" section. 

![image](https://user-images.githubusercontent.com/3258579/212583125-fb7b1179-a17f-4069-9b9b-3faf13725a46.png)

**Comment by gocadimic** [comment]
The content has been added in the Paragraph section.
Please review at ea977c5f52596621f7ca572ddcda38262aca90cb.

**Comment by jpradocueva** [comment]
PR #11 merge
