### ISSUE TITLE
Add links to text descriptors inside of a table

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/markdown_guidelines#7]
![image](https://user-images.githubusercontent.com/3258579/212583483-0d097c0e-dd56-4bf0-b1f8-1aa3d623ee57.png)

Each type of text needs to be pointed to an explanation inside of the sections Table, https://markdown.standardshub.io/md2html-extended#tables

**Comment by jpradocueva** [comment]
@gocadimic we are ready for this Pull Request. We will insert the tables describing markdown elements in this wiki and in the oma-working-groups.
Please prepare the request with the URLs to each constructor. Remember, that we have a problem with missing the filename.

**Comment by gocadimic** [comment]
Resolved in PR #38 and #36.
